name: agents

services:
  mechanic:
    image: node:lts-alpine
    working_dir: /home/node/app/packages/api
    command: npm start
    ports:
      - 3000:3000
    environment:
      DEBUG: '@agent*'
      PORT: 3000
      AGENT_NAME: 'mechanic'
      AGENT_DESCRIPTION: 'a vehicle mechanic that can solve all your problems related to cars'
      AGENT_PROMPT: 'you are a vehicle mechanic, you know everything about automobiles'
      AGENT_MODEL: 'gpt-4o'
      AGENT_API_KEY: $OPENAI_API_KEY
    volumes:
      - .:/home/node/app

  engine-mechanic:
    depends_on:
      mechanic:
        condition: service_started
    image: node:lts-alpine
    working_dir: /home/node/app/packages/api
    command: npm start
    ports:
      - 3001:3001
    environment:
      DEBUG: '@agent*'
      PORT: 3001
      AGENT_NAME: 'engine-mechanic'
      AGENT_DESCRIPTION: 'an engine mechanic that can solve all your problems related to car engines'
      AGENT_PROMPT: 'you are a vehicle engine mechanic, you know everything about engines'
      AGENT_MODEL: 'gpt-4o'
      AGENT_API_KEY: $OPENAI_API_KEY
      AGENT_PARENT: 'ws://mechanic:3000'
    volumes:
      - .:/home/node/app
    links:
      - mechanic:mechanic

  transmission-mechanic:
    depends_on:
      mechanic:
        condition: service_started
    image: node:lts-alpine
    working_dir: /home/node/app/packages/api
    command: npm start
    ports:
      - 3002:3002
    environment:
      DEBUG: '@agent*'
      PORT: 3002
      AGENT_NAME: 'transmission-mechanic'
      AGENT_DESCRIPTION: 'a transmission mechanic that can solve all your problems related to car transmissions'
      AGENT_PROMPT: 'you are a vehicle transmission mechanic, you know everything about transmissions'
      AGENT_MODEL: 'gpt-4o'
      AGENT_API_KEY: $OPENAI_API_KEY
      AGENT_PARENT: 'ws://mechanic:3000'
    volumes:
      - .:/home/node/app
    links:
      - mechanic:mechanic

