name: agents

services:
  mechanic:
    image: node:lts-alpine
    working_dir: /home/node/app/packages/api
    command: npm start
    ports:
      - 3000:3000
    environment:
      DEBUG: '@agent*'
      PORT: 3000
      AGENT_NAME: 'mechanic'
      AGENT_DESCRIPTION: 'ask vehicle mechanic a question about vehicles'
      AGENT_PROMPT: 'you are a vehicle mechanic, you know everything about automobiles. When calling tools, always provide required parameters!'
      AGENT_MODEL: 'gpt-4o'
      AGENT_API_KEY: $OPENAI_API_KEY
    volumes:
      - .:/home/node/app

  engine-mechanic:
    depends_on:
      mechanic:
        condition: service_started
    image: node:lts-alpine
    working_dir: /home/node/app/packages/api
    command: npm start
    ports:
      - 3001:3001
    environment:
      DEBUG: '@agent*'
      PORT: 3001
      AGENT_NAME: 'engine_mechanic'
      AGENT_DESCRIPTION: 'ask engine mechanic a question about vehicle engines'
      AGENT_PROMPT: 'you are a vehicle engine mechanic, you know everything about engines'
      AGENT_MODEL: 'gpt-4o'
      AGENT_API_KEY: $OPENAI_API_KEY
      AGENT_PARENT: 'ws://mechanic:3000'
    volumes:
      - .:/home/node/app
    links:
      - mechanic:mechanic

  transmission-mechanic:
    depends_on:
      mechanic:
        condition: service_started
    image: node:lts-alpine
    working_dir: /home/node/app/packages/api
    command: npm start
    ports:
      - 3002:3002
    environment:
      DEBUG: '@agent*'
      PORT: 3002
      AGENT_NAME: 'transmission_mechanic'
      AGENT_DESCRIPTION: 'ask transmission mechanic a question about vehicle transmissions'
      AGENT_PROMPT: 'you are a vehicle transmission mechanic, you know everything about transmissions'
      AGENT_MODEL: 'gpt-4o'
      AGENT_API_KEY: $OPENAI_API_KEY
      AGENT_PARENT: 'ws://mechanic:3000'
    volumes:
      - .:/home/node/app
    links:
      - mechanic:mechanic

  automatic-transmission-mechanic:
    depends_on:
      transmission-mechanic:
        condition: service_started
    image: node:lts-alpine
    working_dir: /home/node/app/packages/api
    command: npm start
    ports:
      - 3003:3003
    environment:
      DEBUG: '@agent*'
      PORT: 3003
      AGENT_NAME: 'automatic_transmission_mechanic'
      AGENT_DESCRIPTION: 'ask automatic transmission mechanic a question about automatic vehicle transmissions'
      AGENT_PROMPT: 'you are an automatic vehicle transmission mechanic, you know everything about automatic transmissions'
      AGENT_MODEL: 'gpt-4o'
      AGENT_API_KEY: $OPENAI_API_KEY
      AGENT_PARENT: 'ws://transmission-mechanic:3002'
    volumes:
      - .:/home/node/app
    links:
      - transmission-mechanic:transmission-mechanic

  manual-transmission-mechanic:
    depends_on:
      transmission-mechanic:
        condition: service_started
    image: node:lts-alpine
    working_dir: /home/node/app/packages/api
    command: npm start
    ports:
      - 3004:3004
    environment:
      DEBUG: '@agent*'
      PORT: 3004
      AGENT_NAME: 'manual_transmission_mechanic'
      AGENT_DESCRIPTION: 'ask manual transmission mechanic a question about manual vehicle transmissions'
      AGENT_PROMPT: 'you are an manual vehicle transmission mechanic, you know everything about manual transmissions'
      AGENT_MODEL: 'gpt-4o'
      AGENT_API_KEY: $OPENAI_API_KEY
      AGENT_PARENT: 'ws://transmission-mechanic:3002'
    volumes:
      - .:/home/node/app
    links:
      - transmission-mechanic:transmission-mechanic

